# Site settings
title: Red Eclipse
game_version: "1.6.0"
game_release: "Sunset Edition"
game_date: "21st December 2017"
game_youtube: oJRZHjyj7Zg

# Navigation bar
navigation:
  - url: /download
    title: "Downloads"
    class: "fas fa-download"
  - url: /docs
    title: "Beta Documentation"
    class: "fas fa-flask"
  - url: /wiki
    title: "Documentation"
    class: "fas fa-book"
  - url: /apply
    title: "Account Application"
    class: "fas fa-user-plus"
  - url: /discuss
    title: "Discussion Area"
    class: "fas fa-quote-left"
  - url: /chat
    title: "Live Chat"
    class: "fas fa-comments"
  - url: /discord
    title: "Discord Server"
    class: "fab fa-discord"
  - url: /messenger
    title: "Facebook Messenger"
    class: "fab fa-facebook-messenger"
  - url: /issues
    title: "Issue Tracker"
    class: "fas fa-tasks"
  - url: /contribute
    title: "Contribution Guidelines"
    class: "fas fa-handshake"
  - url: /stats
    title: "Game Statistics"
    class: "fas fa-chart-bar"
  - url: /servers
    title: "Server List"
    class: "fas fa-server"
  - url: /reddit
    title: "Official SubReddit"
    class: "fab fa-reddit"
  - url: /facebook
    title: "Facebook Page"
    class: "fab fa-facebook"
  - url: /youtube
    title: "YouTube Page"
    class: "fab fa-youtube"
  - url: /github
    title: "GitHub Project"
    class: "fab fa-github"
  - url: /patreon
    title: "Subscribe via Patreon"
    class: "fab fa-patreon"
  - url: /donate
    title: "Donate via PayPal"
    class: "fab fa-paypal"

# Where things are
source: "."
collections_dir: "pages"
plugins_dir: "plugins"
layouts_dir: "layouts"
data_dir: "data"
includes_dir: "includes"

# Handling Reading
safe: true
exclude:
  - ".github"
  - "plugins"
  - "layouts"
  - "data"
  - "includes"
  - "_config.yml"
  - "CNAME"
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

# Filtering Content
show_drafts: null
limit_posts: 0
future: false
unpublished: false

# Plugins
plugins:
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Outputting
# permalink: date
# paginate_path: /page:num
# timezone: null

# Markdown Processors
kramdown:
    auto_ids: true
    entity_output: as_char
    toc_levels: 1..6
    smart_quotes: lsquo,rsquo,ldquo,rdquo
    input: GFM
    hard_wrap: false
    footnote_nr: 1
    show_warnings: false

# Relative links
relative_links:
  enabled: true
  collections: false
