# Site settings
title: Red Eclipse
game_version: "1.5.8"
game_release: "Elysium Edition"
game_date: "14th December 2017"

# Where things are
source: "."
collections_dir: "pages"
plugins_dir: "bits/plugins"
layouts_dir: "bits/layouts"
data_dir: "bits/data"
includes_dir: "bits/includes"

# Handling Reading
safe: true
exclude:
  - ".github"
  - "_config.yml"
  - "CNAME"
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

# Filtering Content
show_drafts: null
limit_posts: 0
future: false
unpublished: false

# Plugins
plugins:
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-sitemap
  - jemoji

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Outputting
# permalink: date
# paginate_path: /page:num
# timezone: null

# Markdown Processors
kramdown:
    auto_ids: true
    entity_output: as_char
    toc_levels: 1..6
    smart_quotes: lsquo,rsquo,ldquo,rdquo
    input: GFM
    hard_wrap: false
    footnote_nr: 1
    show_warnings: false
